### ISSUE TITLE
[Error]报错：The future belongs to a different loop than the one specified as the loop argument

### ISSUE THREAD

**Issue by Senvlin** [CcendercatcC/KOOK---PYCBot-API#1]
![image](https://user-images.githubusercontent.com/103633974/218221711-7e11f4fc-4b2d-4f49-b0ab-d0c1a0595070.png)
我clone下来了一份源代码，并把GetWay的token参数改成我自己的机器人的token后报错了。初步判断是在Receive函数中的`websocket.recv()`出了问题
---
**Somethings:**
Python Version：3.10.9
OS：Windows

**Comment by Senviln** [comment]
我clone下来了一份源代码，并把GetWay的token参数改成我自己的机器人的token后报错了。初步判断是在Receive函数中的`websocket.recv()`出了问题

**Comment by Senviln** [comment]
Python Version：3.10.9

**Comment by Senviln** [comment]
OS：Windows

**Comment by Senvlin** [comment]
去看了一下Websockets库的issues，发现也有个人[提出了差不多的issue](https://github.com/aaugustin/websockets/issues/800)。根据原作者的 theories 和PYCBot的源代码来看，应该是`websockets.connect`没有正确的关闭导致的报错。待会我会交一个pr上去，把这个问题修复一下(
