### ISSUE TITLE
[Error]object bytes can't be used in 'await' expression

### ISSUE THREAD

**Issue by Senvlin** [CcendercatcC/KOOK---PYCBot-API#2]
![image](https://user-images.githubusercontent.com/103633974/218225245-3603ae12-30ce-4de4-96c1-9b57fcaab7d0.png)
在测试代码的时候又报错了，[zlib模块](https://docs.python.org/3/library/zlib.html)本身就不是异步的吧……
待会会和[这个issue](https://github.com/CcendercatcC/KOOK---PYCBot-API/issues/1)的pr一起交上去
---
Something：
Python Version：3.10.9
OS：Windows

**Comment by CcendercatcC** [comment]
抱歉 本人使用的python版本是3.11.1 所以貌似没有发现该问题，待会就改
